import { ImageEntry } from "@/interface/imageInterface";

export const imageList: ImageEntry[] = [
  { name: "logo_black_01", key: "LogoPrincipalBlack.png" },
  { name: "logo_white_02", key: "logoPrincipalWhite.png" },
  { name: "home_01", key: "Home_01.webp" },
  { name: "info_01", key: "info_01.png" },
  { name: "info_02", key: "info_02.png" },
  { name: "info_03", key: "info_03.png" },
  { name: "info_04", key: "info_04.png" },
  { name: "side_info_01", key: "side_info_01.webp" },
  { name: "side_info_02", key: "side_info_02.webp" },
  { name: "side_info_03", key: "side_info_03.webp" },
  { name: "side_info_04", key: "side_info_04.webp" },
  { name: "side_info_05", key: "side_info_05.webp" },
  { name: "side_info_06", key: "side_info_06.webp" },
  { name: "side_info_07", key: "side_info_10.jpg" },
  { name: "side_info_08", key: "side_info_08.webp" },
  { name: "side_info_09", key: "side_info_09.webp" },
  { name: "empresa_01", key: "empresa_01.webp" },
  { name: "empresa_02", key: "empresa_02.webp" },
  { name: "empresa_03", key: "empresa_03.webp" },
  { name: "empresa_04", key: "empresa_04.webp" },
  { name: "empresa_05", key: "empresa_05.webp" },
  { name: "empresa_06", key: "empresa_06.webp" },
  // { name: "candidatos_01", key: "candidatos_01.webp" },
  // { name: "candidatos_02", key: "candidatos_02.webp" },
  // { name: "nosotros_01", key: "nosotros_01.webp" },
  // { name: "nosotros_02", key: "nosotros_02.webp" },
];
